common:
  languages:
    - key: en_US
      progress: 100
      name: English
    - key: fr
      progress: 99
      name: Français
      author: 'MichaelS, Its1tom'
    - key: id
      progress: 90
      name: Bahasa Indonesia
      author: Zuhh
    - key: tr
      progress: 98
      name: Türkçe
    - key: es_ES
      progress: 0
      name: Español
      author: aleksa1
dev:
  serverURL: 'http://127.0.0.1:3001'
  serverAPIURL: 'http://127.0.0.1:3001/BrainlyTools'
  shortenedLinkURL: 'http://127.0.0.1:3001/l'
  uploadedFilesURL: 'http://127.0.0.1:3001/files/uploaded/'
production:
  serverURL: 'https://sahin.in'
  serverAPIURL: 'https://sahin.in/BrainlyTools'
  shortenedLinkURL: 'http://sahin.in/l'
  uploadedFilesURL: 'http://sahin.in/files/uploaded/'
