common:
  languages:
    en_US:
      progress: 100
      name: English
      author: null
    fr:
      progress: 94
      name: Français
      author: 'MichaelS, Its1tom'
    id:
      progress: 86
      name: Bahasa Indonesia
      author: Zuhh
    tr:
      progress: 96
      name: Türkçe
      author: null
    es_ES:
      progress: 0
      name: Español
      author: aleksa1
    pt_BR:
      progress: 0
      name: Portuguese
      author: C
dev:
  serverURL: 'http://localhost:3001'
  serverAPIURL: 'http://localhost:3001/BrainlyTools'
  shortenedLinkURL: 'http://localhost:3001/l'
  uploadedFilesURL: 'http://localhost:3001/files/uploaded/'
production:
  serverURL: 'https://sahin.in'
  serverAPIURL: 'https://sahin.in/BrainlyTools'
  shortenedLinkURL: 'http://sahin.in/l'
  uploadedFilesURL: 'http://sahin.in/files/uploaded/'
